config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("polls.urls")),
]

polls/urls.py
from django.urls import path

from . import views


app_name = "polls"

urlpatterns = [
    path("", views.home, name="home"),
    path("polling_units/", views.polling_units, name="polling_units"),
    path("polling_units/<int:unit_id>/", views.unit_results, name="unit_results"),
    path("lga_results/", views.lga_results, name="lga_results"),
    path("add_results/", views.add_results, name="add_results"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <style>
        .w-5{
            min-width: 6rem;
        }
    </style>
    <title>Bincom Test</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand text-primary" href="{% url "polls:home" %}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link text-primary" aria-current="page" href="{% url "polls:polling_units" %}">
                    Polling unit results
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-primary" href="{% url "polls:lga_results" %}">Total LGA results</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-primary" href="{% url "polls:add_results" %}">Add results</a>
            </li>
        </ul>
        </div>
    </div>
    </nav>
    <main class="container">
        <header class="pb-2 mb-2 mt-5 border-bottom">
            {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                    <p{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</p>
                    {% endfor %}
                </ul>
            {% endif %}
            {% block page_header %}Welcome{% endblock page_header %}
        </header>
        {% block content %}{% endblock content %}
    </main>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block page_header %}
  <div class="p-3 mb-4 bg-light border rounded-3">
    <div class="container-fluid py-4">
      <h1 class="display-3">2011 INEC Election</h1>
      
      <p class="lead">
        Welcome to 2011 INEC national election coalation center.
        <br>
        Here you can track the on going election result and new polling units results are also 
        registered here. 
      </p>

      
    </div>
  </div>
{% endblock page_header %}